[project]
name = "invenio-rdm-starter"
version = "14.0.0.0"
description = "Starter for the invenio-rdm turn-key research data management repository"
authors = [{ name = "Martin Fenner", email = "martin@front-matter.de" }]
readme = "README.md"
requires-python = ">=3.14"
license = "MIT"
dependencies = [
    "invenio-app-rdm>=14.0.0,<15.0",
    "invenio-search[opensearch2]>=3.1.2,<3.2.0",
    "invenio-s3>=3.0.2",
    "invenio-oauthclient",
    "setuptools>=70,<81",
    "gunicorn~=23.0.0",
    "commonmeta-py[backend]>=0.269,<1",
    "commonmeta-rs>=0.9.75",
    "invenio-pidbox>=0.1.24,<1",
    "invenio-feeds>=0.1.16,<1",
    "invenio-logging",
    "structlog>=25.0",
    "prometheus-flask-exporter>=0.23.1",         # no [sentry] extra
    "sentry-sdk[flask]>=2.0,<3",
    "structlog-sentry>=2.1.0",
    "nh3>=0.2",
]

[tool.uv.sources]
invenio-oauthclient = { git = "https://github.com/front-matter/invenio-oauthclient", branch = "contrib-oidc" }

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = ["pytest>=8.4.2", "pytest-invenio>=4.0.0", "ruamel-yaml>=0.19.1"]

[tool.hatch.build]
include = ["site/invenio_rdm_starter/*.py"]

[tool.hatch.build.targets.wheel]
sources = { "site" = "" }

[project.entry-points."invenio_base.blueprints"]
invenio_rdm_starter = "invenio_rdm_starter.views:create_blueprint"

[project.entry-points."invenio_base.api_blueprints"]
invenio_rdm_starter = "invenio_rdm_starter.views:create_api_blueprint"

[tool.ruff]
line-length = 79
include = ["pyproject.toml", "site/**/*.py"]

[project.optional-dependencies]
docs = ["mkdocs-material>=9.7.0"]
actions = ["commonmeta-py[backend]>=0.269,<1"]
